---
on:
  pull_request:
  push:
  schedule:
    # execute once a day, the 1st
    - cron: 10 9 * * *
env:
  PHAN_CONFIG: ${{ github.event.schedule && 'dev/tools/phan/config_extended.php' || 'dev/tools/phan/config.php' }}
  PHAN_BASELINE: dev/tools/phan/baseline.txt
  PHAN_MIN_PHP: 7.0
name: phan
jobs:
  phan:
    name: Run phan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none  # disable xdebug, pcov
          tools: cs2pr,phan
      - name: Run Phan analysis
        run: |
          phan --quick -k $PHAN_CONFIG -B $PHAN_BASELINE --analyze-twice --minimum-target-php-version $PHAN_MIN_PHP --output-mode=checkstyle -o _phan.xml
      - name: Add results to PR
        if: ${{ always() }}
        run: |
          cs2pr --prepend-filename --prepend-source --notices-as-warnings _phan.xml
      - name: Provide phan log as artifact
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: phan-srcrt
          # path: ${{ github.workspace }}/phan.log
          path: ${{ github.workspace }}/_phan.xml
          retention-days: 2
